/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "APIFY_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AllEventsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AuthorizerTokensTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "BSKY_PASSWORD": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CrawledEventsQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "EVENTS_INGEST_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "EventsPlannerApi": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "EventsProcessorStateMachine": {
      "arn": string
      "id": string
      "type": "sst.aws.StateMachine"
    }
    "ExtractFeaturesFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GenerateTweetEventFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "NOTION_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostPublisherStateMachine": {
      "arn": string
      "id": string
      "type": "sst.aws.StateMachine"
    }
    "PostStatusTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "PostTweetEventFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ProcessFeaturesFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RetrieveFromApifyFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RetrieveRelevantEventsFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SaveToAllFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UpdatesProcessorStateMachine": {
      "arn": string
      "id": string
      "type": "sst.aws.StateMachine"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}